### PR TITLE
Add MutationState to riverpod

### PR DESCRIPTION
**Pull request by TekExplorer**
Adds non-generator mutations for #1660 

-- from [TekExplorer/riverpod_mutations](https://github.com/TekExplorer/riverpod_mutations) which is available in the meantime as `riverpod_mutations` on pub.dev

Tests could be better, but the model does work.

### CODE REVIEW

**Comment by rrousselGit** [comment]
Note that mutations are supposed to modify a provider.
Here what you shared is only a separate state

Mutations would be more like:

```dart
final provider = Provider<int>((ref) => ...);

int value = ref.watch(provider);
Mutation<int> increment = ref.watch(provider.mutation('increment'));

increment((state) => state + 1);
```

**Comment by TekExplorer** [comment]
> 

It would be easy enough to `typedef Mutation<T> = MutationState<T, FutureOr<T> Function()>;`
but as far as applying mutations goes to actual providers, where should i be looking to modify?
(as a side note, this state class should be generator friendly as long as you get parameters passed in somehow isnt it?)

**Comment by TekExplorer** [comment]
> > It would be easy enough to typedef Mutation = MutationState<T, FutureOr Function()>;
> 
> The class name doesn't really matter here :)
> 
> > but as far as applying mutations goes to actual providers, where should i be looking to modify?
> 
> You can look at how AsyncNotifierProvider implements its `provider.notifier` / `provider.future`

I see that they use a so called `ProxyElementValueNotifier`

`mutation` in your example clearly is either a function or callable class

my concern arises with the fact that mutations are decoupled from the notifier's state, so i dont really know where to start

I'm guessing this will need to be a mixin of some sort like how the future is.

the key parameter, how will that play in? I know how to do it by creating more providers, but not embedding it into the providers directly

**Comment by TekExplorer** [comment]
side note: `futureNotifier` doesnt appear to be private as it implies

**Comment by rrousselGit** [comment]
You don't need a mixin. You can put the logic on ProviderElementBase and ProviderBase

This will enable it for all widgets

**Comment by TekExplorer** [comment]
> You don't need a mixin. You can put the logic on ProviderElementBase and ProviderBase
> 
> This will enable it for all providers

something along the lines of:

provider_base.dart
```dart
...
  Refreshable<Mutation<T>> mutation<T>(String key) {
    return _mutation(this, key);
  }

  ProviderElementProxy<State, Mutation<T>> _mutation<T>(
    ProviderBase<State> that,
    Object key,
  ) {
    return ProviderElementProxy(
      that,
      (element) => element._mutationNotifier(key),
    );
  }
...
```

element.dart => ProviderElementBase
```dart
...
  // key as Object? String?
  ProxyElementValueNotifier<Mutation<T>> _mutationNotifier<T>(Object key) {
    return _mutations.putIfAbsent(
      key,
      () {
        final notifier = ProxyElementValueNotifier<Mutation<T>>();
        notifier.result = Result.data(Mutation<T>.initial(
          // instead of passing in ref, pass in a setter, as thats all we actually need. also makes it reusable like AsyncValue
          (state) => notifier.result = Result.data(state),
          (p) => p(),
        ));
        return notifier;
      },
      // TODO(TekExplorer) this cast is necessary for typing... is this safe? is there some better way? do we type at all?
    ) as ProxyElementValueNotifier<Mutation<T>>;
  }

  final _mutations = <Object, ProxyElementValueNotifier<Mutation<Object?>>>{};
...
```

just trying to see if i'm heading in the right direction

**Comment by rrousselGit** [comment]
That could work yes.

Although I'll admit I'm not fond of this enabling any provider to be mutated from anywhere. I prefer a way to have "notifiers" manually expose mutations.

**Comment by TekExplorer** [comment]
> That could work yes.
> 
> Although I'll admit I'm not fond of this enabling any provider to be mutated from anywhere. I prefer a way to have "notifiers" manually expose mutations.

>> You don't need a mixin. You can put the logic on ProviderElementBase and ProviderBase
>>
>>This will enable it for all providers

??????

I mean, the provider isn't really getting directly mutated. It just tracks the state of an arbitrary function call


The question arises; how can a Notifier tell the Provider[Element] about mutations?
Or should instead the notifier expose mutations in the shape of `final addTodo = ref.watch(someProvider.notifier.mutate(key))`?
or... i suppose it could just be on `NotifierProvider`s directly with `final addTodo = ref.watch(someProvider.mutate(key))`

**Comment by rrousselGit** [comment]
> I mean, the provider isn't really getting directly mutated. It just tracks the state of an arbitrary function call

It should though.  
Mutations are supposed to mutate the provider. If they don't, they aren't mutations :) 

> The question arises; how can a Notifier tell the Provider[Element] about mutations?
Or should instead the notifier expose mutations in the shape of final addTodo = ref.watch(someProvider.notifier.mutate(key))?
or... i suppose it could just be on NotifierProviders directly with final addTodo = ref.watch(someProvider.mutate(key))

Well I don't know. It's kind of why I haven't offered a way to do mutations without codegen


With codegen I was thinking of having:

```dart
@riverpod
class Foo extends _$Foo {
...
  @mutation
  Result fn() => Result();
}

Mutation<Result> fn = ref.watch(fooProvider.fn);
```

**Comment by TekExplorer** [comment]
> > I mean, the provider isn't really getting directly mutated. It just tracks the state of an arbitrary function call
> 
> It should though. Mutations are supposed to mutate the provider. If they don't, they aren't mutations :)
> 
> > The question arises; how can a Notifier tell the Provider[Element] about mutations?
> > Or should instead the notifier expose mutations in the shape of final addTodo = ref.watch(someProvider.notifier.mutate(key))?
> > or... i suppose it could just be on NotifierProviders directly with final addTodo = ref.watch(someProvider.mutate(key))
> 
> Well I don't know. It's kind of why I haven't offered a way to do mutations without codegen
> 
> With codegen I was thinking of having:
> 
> ```dart
> @riverpod
> class Foo extends _$Foo {
> ...
>   @mutation
>   Result fn() => Result();
> }
> 
> Mutation<Result> fn = ref.watch(fooProvider.fn);
> ```

(I think I tried to respond to this like 3 different times on different devices and never hit send :p)
I could easily see the generator adding something like this to the generated provider:

```dart
...SomeProvider
  // probably could be done better
  final _fnKey = Object();
  Refreshable<Mutation<SomeType>> get fn => _mutation(this, _fnKey);
...

 ProviderElementProxy<State, Mutation<T>> _mutation<T>(
    ProviderBase<State> that,
    Object key,
  ) {
    return ProviderElementProxy(
      that,
      (element) => element._mutationNotifier(key),
    );
  }
```
though obviously not *exactly* like this since the notifier is currently private.

so perhaps mutations could be *internally* added to all providers and only accessed by the generator (and anyone crazy enough to do it manually)?

**Comment by TekExplorer** [comment]
A side question, what about disposing of mutation states?
would mutations dispose automatically for everything, for only autodispose providers, or is it something that could be configurable per-mutation?

**Comment by rrousselGit** [comment]
They should behave like autoDispose providers only.

**Comment by RodolfoSilva** [comment]
@TekExplorer this is the same code of: [riverpod_mutations](https://github.com/TekExplorer/riverpod_mutations)? Or the [riverpod_mutations](https://github.com/TekExplorer/riverpod_mutations) is more updated?

**Comment by RodolfoSilva** [comment]
@TekExplorer this is the same code of: [riverpod_mutations](https://github.com/TekExplorer/riverpod_mutations)? Or the [riverpod_mutations](https://github.com/TekExplorer/riverpod_mutations) is more updated?

**Comment by rrousselGit** [comment]
Closing as I don't plan on merging this for now :)

**Comment by titomitto** [comment]
Do you still have plans of supporting Mutations?
Is there a way I can use this right now. The current process you documented on riverpod 2 documentation it hectic

**Comment by TekExplorer** [comment]
@titomitto You can use my `riverpod_mutations` package which handles it in a good-enough manner until an official means is introduced

**Pull request closed without merging**
