### PR TITLE
Docs Russian l10n

### PR DESCRIPTION
**Pull request by bytes7bytes7**
Translated site docs to Russian language

### CODE REVIEW

**Comment by bytes7bytes7** [comment]
@rrousselGit , can you check this PR? 👉👈

**Comment by rrousselGit** [comment]
Sorry! Looking good :)

**Comment by bytes7bytes7** [comment]
@rrousselGit , there is not russian docs on the site😔 Did I miss something? Or you have not updated it yet?

**Comment by rrousselGit** [comment]
Ah, you didn't add "ru" in the list of languages.
I've added it

**Comment by bytes7bytes7** [comment]
Still no russian on the site(

**Comment by rrousselGit** [comment]
@bytes7bytes7 The build is failing because russian docs have incorrect links
Do you mind fixing the errors?

https://app.netlify.com/sites/river-pod/deploys/6373d3f8b2fd3e0008ae579f

**Comment by bytes7bytes7** [comment]
Ok, I will try to fix it

**Pull request merged**
