### PR TITLE
Update concept reading page code examples

### PR DESCRIPTION
**Pull request by leehack**
Update concept reading page examples with options

### CODE REVIEW

**Comment by rrousselGit** [comment]
Hello, thanks for this!

The CI seems to be failing. Can you have a look?

**Comment by leehack** [comment]
@rrousselGit It seems I can't see the logs why it failed. Probably I don't have permission to access the `netlify`. Would you mind copying the logs here so that I can address them?

**Comment by leehack** [comment]
@rrousselGit It's fixed now.

**Comment by rrousselGit** [comment]
Thanks!

**Pull request merged**
