### PR TITLE
docs(v2): refactor Chinese translations

### PR DESCRIPTION
**Pull request by escwxyz**
- refactor introduction
- refactor getting started

### CODE REVIEW

**Comment by rrousselGit** [comment]
The CI is failing, quite possibly because of broken links. Could you fix it?

**Comment by escwxyz** [comment]
> The CI is failing, quite possibly because of broken links. Could you fix it?

Thanks, what else should I do? Looks like I have to run the script `dart ./src/outdated_docs_generator.dart` before committing.

**Comment by escwxyz** [comment]
> The CI is failing, quite possibly because of broken links. Could you fix it?

Hi, thanks! Before proceeding, want to know if it means that I missed some JSX components, inside the `getting_started` folder? Or do you mean the url links inside the markdown contents?

**Comment by rrousselGit** [comment]
The failing CI steps should contain logs about whatever the problem is. Have a look at it :)

**Comment by escwxyz** [comment]
> The failing CI steps should contain logs about whatever the problem is. Have a look at it :)

Yeah I know, it failed firstly due to the `outdated_translations` JS file before you added changes. 

But right now the netlify deploy logs are not clear to me, 

`Build failed due to a user error: Build script returned non-zero exit code: 2` without further info. 

```
4:54:15 PM:   "build.command" failed                                        
4:54:15 PM: ────────────────────────────────────────────────────────────────
4:54:15 PM: ​
4:54:15 PM:   Error message
4:54:15 PM:   Command failed with exit code 1: npm run build (https://ntl.fyi/exit-code-1)
```


Or did I miss something?

**Comment by rrousselGit** [comment]
True, the logs aren't very helpful actually.
You could try running `npm run build` locally to reproduce the error.

**Comment by escwxyz** [comment]
@rrousselGit not sure what's the issue here, maybe check out this https://github.com/actions/checkout/issues/417, the site is fine built locally.

**Comment by rrousselGit** [comment]
Restarting the CI fixed it.

Thanks a lot for your work! :)

**Pull request merged**
