### PR TITLE
Fix DioError analyzer warning causing builds to fail

### PR DESCRIPTION
**Pull request by kwilliams3**

### CODE REVIEW

**Comment by kwilliams3** [comment]
image

**Comment by rrousselGit** [comment]
It's already fixed on master. Pulling changes should be fine.

**Comment by kwilliams3** [comment]
> It's already fixed on master. Pulling changes should be fine.

Oh, perfect. Can you merge master into docs-v2?

**Comment by rrousselGit** [comment]
Sure. Although if need be, you could do that in your PRs too. But I'll do it

**Comment by kwilliams3** [comment]
Wouldn't every PR based on docs-v2 have to do that as well? Perhaps there's not many PRs contributing to the second version of docs.

**Pull request closed without merging**
