### PR TITLE
[docs-v2] Save toogle state

### PR DESCRIPTION
**Pull request by CaiJingLong**
Save Toogle state for "Code generation" and "flutter_hooks" for docs

### CODE REVIEW

**Comment by rrousselGit** [comment]
Good idea!

Could you refactor the logic to replace `useState` into a `useSavedState`?

**Comment by CaiJingLong** [comment]
> Good idea!
> 
> Could you refactor the logic to replace `useState` into a custom `useSavedState`?

Which folder should I place this hooks function in?

**Comment by CaiJingLong** [comment]
At present, the method is still placed under the same file.
If you think it needs to be extracted to a separate file, you can continue to provide review comments.

**Comment by rrousselGit** [comment]
> Which folder should I place this hooks function in?

Doesn't matter. Wherever you feel is appropriate. They can move over time

> Also, does the key of local storage need to be defined in a separate const file?

No, it should be a hook parameter.

**Comment by rrousselGit** [comment]
If we ever want to reuse the "key", we should likely instead make a reusable hook associated with the key.

Like. `function useHookState() => useSavedState('key', default)`
We'd share that instead

**Comment by rrousselGit** [comment]
It appears that the website build is failing. Could you fix it?

**Comment by CaiJingLong** [comment]
> It appears that the website build is failing. Could you fix it?

Looks like the docusaurus is s SSR framework, the effect of `BrowserOnly` looks like it might break SSR.
And since this Hooks function is for Codegen, will it affect all sites?

**Comment by CaiJingLong** [comment]
Build CI failed, it seems that github's token is used too frequently.
If this kind of problem happens frequently, consider adding path filter to workflows, the [doc of github action](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore).

**Comment by rrousselGit** [comment]
LGTM thanks!

**Pull request merged**
