### PR TITLE
fix: migrate MaterialStateProperty usage

### PR DESCRIPTION
**Pull request by drown0315**
Migrated all usages of `MaterialStateProperty.all`, This is because MaterialStateProperty.all will be deprecated in the future.  just only change `example` and `websites`, so does not update `CHANGELOG.md`
refer to: https://github.com/dart-lang/sdk/issues/49056.
image

e.g.
Replace `MaterialStateProperty.all` to `MaterialStatePropertyAll
`
Before:
```
            ElevatedButton(
              style: ButtonStyle(
                // If there is an error, we show the button in red
                backgroundColor: MaterialStateProperty.all(
                  isErrored ? Colors.red : null,
                ),
              ),
```

After:
```
            ElevatedButton(
              style: ButtonStyle(
                // If there is an error, we show the button in red
                backgroundColor: MaterialStatePropertyAll(
                  isErrored ? Colors.red : null,
                ),
              ),
```

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).

- [ ] I have updated the `CHANGELOG.md` of the relevant packages.
      Changelog files must be edited under the form:

  ```md
  ## Unreleased fix/major/minor

  - Description of your change. (thanks to @yourGithubId)
  ```

- [x] If this contains new features or behavior changes,
      I have updated the documentation to match those changes.

### CODE REVIEW

**Comment by rrousselGit** [comment]
Hello!

There are a few conflicts :)
I personally migrated to WidgetsStateProperty instead

**Comment by drown0315** [comment]
Just noticed that you have already completed the migration.

I have resolved these conflicts.

I found that `WidgetStateProperty` has not been released in the latest stable version of Flutter yet, which may cause errors for many developers running examples, so I think temporarily using `MaterialStatePropertyAll` might be a better option.

**Comment by drown0315** [comment]
Just noticed that you have already completed the migration.

I have resolved these conflicts.

I found that WidgetStateProperty has not been released in the latest stable version of Flutter yet, which may cause errors for many developers running examples, so I think temporarily using MaterialStatePropertyAll might be a better option.

**Comment by rrousselGit** [comment]
I've already migrated the english variant to use WidgetsStateProperty.

I prefer being on the edge in terms of feature, because otherwise we'll have to updates the docs again later.

**Comment by drown0315** [comment]
Okay, I have updated.
I replace all occurrences of `MaterialStateProperty.all` with `WidgetStatePropertyAll`

**Comment by rrousselGit** [comment]
LGTM

**Pull request merged**
