### PR TITLE
Docs v2

### PR DESCRIPTION
**Pull request by mboyamike**
This adds code generation and raw code snippets for the following pages:

1. concepts/why immutability
2. concepts/provider lifecycles

### CODE REVIEW

**Comment by rrousselGit** [comment]
The CI seems to be failing, likely due to broken links. Could you fix this?

**Comment by mboyamike** [comment]
> The CI seems to be failing, likely due to broken links. Could you fix this?

Yeah. I'll fix it

**Comment by mboyamike** [comment]
Fixed 😄

**Comment by rrousselGit** [comment]
Great! Thanks :)

**Pull request merged**
