### PR TITLE
[riverpod_lint] Add new lint avoid_generated_classes_as_return_type

### LINKED ISSUE #2359: lint: Warn if the return value of a provider is a generated type (which could generate `dynamic`)
Related to https://github.com/rrousselGit/riverpod/issues/2273

riverpod_generator doesn't support generated types well yet and instead emits `dynamic`.
To help spot the inconvenience, a warning could be implemented to warn against doing:

```dart
@riverpod
GeneratedClass example(ref) => ...
```

### PR DESCRIPTION
**Pull request by charlescyt**
An attempt to close #2359

### CODE REVIEW

**Comment by rrousselGit** [comment]
This is great, but I was thinking about straight up fixing this instead. Riverpod_generator should be able to fix this (although for Freezed, that's more complex).

**Comment by charlescyt** [comment]
Sure, if it is going to be fixed, then there is no need for this lint.
Should I close the PR?

**Comment by rrousselGit** [comment]
I'll investigate today the possibility of a fix and come back to you asap

**Comment by rrousselGit** [comment]
I have successfully managed to support generated types. So I'll close this.

Thanks for your PR though! Your effort didn't go unnoticed :)

**Pull request closed without merging**
