### PR TITLE
Added avoid_buildcontext_in_provider lint

### PR DESCRIPTION
**Pull request by dhruv1710**
PR for issue number #2187

### CODE REVIEW

**Comment by rrousselGit** [comment]
Hello!
The changes don't do anything my themselves. Is this still work in progress?

**Comment by dhruv1710** [comment]
Is there any configuration I missed?

**Comment by rrousselGit** [comment]
You need to implement "run" and add the list to PluginBqse.getLints

**Comment by dhruv1710** [comment]
I'm stuck in implementing run. How will I find what all is passed in the arguments of the function.

**Comment by rrousselGit** [comment]
Look at the source of other lints (such as "provider_parameters") . This should give you plenty of ideas on how to do it

**Comment by dhruv1710** [comment]
I there a way to test the lint which I made on code.

**Comment by rrousselGit** [comment]
Yes. Look at riverpod_lint_flutter_test

Testing lints is done through expect_lint.

**Comment by rrousselGit** [comment]
:wave: I'll close this since this PR isn't working yet.

Feel free to open a new PR once you get something working

**Pull request closed without merging**
