### PR TITLE
fix paths to CodeSnippet in ru i18n

### PR DESCRIPTION
**Pull request by bytes7bytes7**

### CODE REVIEW

**Comment by rrousselGit** [comment]
Epic! That should do it this time

**Comment by bytes7bytes7** [comment]
No, smth is wrong

**Comment by rrousselGit** [comment]
Weird. I literally saw them appear in the deploy preview.

**Comment by rrousselGit** [comment]
Ok, netlify wrongly thought there was no content change so aborted the deploy..

I've forcibly triggered a deploy. They should appear in a few minutes.

**Comment by rrousselGit** [comment]
There you go, the docs are live. We do see russian now. Thanks for your work!

**Comment by bytes7bytes7** [comment]
Nice, man!😎 Thank you for your library💪

**Pull request merged**
