### PR TITLE
Translate document to Chinese.

### PR DESCRIPTION
**Pull request by yang-lile**
translate document by this roadmap.

- [x] base config json file.

### Introduction

- [x] Why Riverpod?
- [x] Getting started

### Riverpod for Providers users

- [x] Quickstart
- [x] Provider vs Riverpod
- [x] Motivation

### Essentials

- [x] Make your first provider/network request
- [x] Performing side effects
- [x] Passing arguments to your requests
- [x] Websockets and synchronous execution
- [x] Combining requests
- [x] Clearing cache and reacting to state disposal
- [x] Eager initialization of providers
- [x] Testing your providers
- [x] Logging and error reporting
- [x] FAQ
- [x] DO/DON'T

### Case studies

- [x] Pull to refresh
- [x] Debouncing/Cancelling network requests

### Advanced topics

- [x] Optimizing performance

### Concepts

- [x]  About code generation
- [x]  About hooks

### Migration guides

- [x] From `StateNotifier`
- [x] From `ChangeNotifier`
- [ ] ^0.14.0 to ^1.0.0
- [ ] ^0.13.0 to ^0.14.0

### Old docs

- [ ]  `concepts 🚧` old docs
- [ ]  `providers 🚧` old docs
- [ ]  `guides 🚧` old docs

### CODE REVIEW

**Comment by laterdayi** [comment]
Look forward to your work

**Comment by laterdayi** [comment]
When is it expected to be completed? Can you release some first

**Comment by yang-lile** [comment]
> When is it expected to be completed? Can you release some first

It might be ready the day after tomorrow. Can I invite you to do a review then?

**Comment by laterdayi** [comment]
I wish I could help, but I'm not familiar with riverpod

**Pull request closed without merging**
