### PR TITLE
docs: code snippets for concepts/combining_providers

### PR DESCRIPTION
**Pull request by mboyamike**
This adds code snippets for the concepts/combining provider states page.

It enables toggling between code generation and the raw way.

To note: I did not use the actual dio package and instead would use a class I made for convenience (Not visible in documentation though). If this is not desired I can switch to dio :)

### CODE REVIEW

**Comment by rrousselGit** [comment]
> To note: I did not use the actual dio package and instead would use a class I made for convenience (Not visible in documentation though). If this is not desired I can switch to dio :)

It'd be better to use `dio` yes.
Could you do that?

**Comment by mboyamike** [comment]
Yes sure. 
I'll make that change

**Comment by mboyamike** [comment]
Now using the actual dio package

**Comment by rrousselGit** [comment]
Great, thanks!

**Pull request merged**
