### PR TITLE
Expose stateOrNull in Notifier

### PR DESCRIPTION
**Pull request by jascodes**
Related #2589

### CODE REVIEW

**Comment by rrousselGit** [comment]
This should use the v3 branch as base.

Also, instead of a stateOrNull, a breaking change should be made to change the current state

**Comment by rrousselGit** [comment]
It needs tests too :)

And this needs to be done on all objects with a "T get state". So Refs too.
But making sure FutureProviderRef.state is still non-nullable

**Comment by jascodes** [comment]
Github don't allow to update the source branch, so will open another PR.

**Comment by jascodes** [comment]
@rrousselGit Now that there is #2592 for riverpod 3, maybe we can still merge stateOrNull property as non-breaking change for riverpod 2?

**Comment by rrousselGit** [comment]
@jascodes I'm not super fond of the idea.

**Comment by rrousselGit** [comment]
Actually, you know what, sure.

But then name it "state2" and deprecate "state" along with it's setter (in favor of setState) 

Then on the v3 branch, we'd remove the deprecated members and rename state2=>state

**Pull request closed without merging**
