### PR TITLE
Adhere Flutter Lint

### PR DESCRIPTION
**Pull request by jpoh281**
#1601

### CODE REVIEW

**Comment by rrousselGit** [comment]
The "key" lint is disabled inside examples, to remove unnecessary lines and focus more on the content.  
If we want to enable it back, the analysis_options.yaml in `examples` should be modified accordingly and all the issues should be fixed.

Fancy doing that?

**Comment by jpoh281** [comment]
I understand why you removed Lint.

But if at any time you think it's better to re-enable it, I'd love to help.

Please close my PR if you don't need it. Thank you!

**Comment by rrousselGit** [comment]
Feel free to update your PR and enable it :)

It's just that, as I mentioned, the analysis_options.yaml should be updated too.

**Comment by rrousselGit** [comment]
Closing as I don't plan on making such change. But your work is appreciated! Better luck next time 😄

**Pull request closed without merging**
