### PR TITLE
Added Turkish language support

### PR DESCRIPTION
**Pull request by talhademirbas**
This PR adds Turkish language support to the Riverpod documentation. The following changes were made:
- Added a new `tr` folder in the `website/i18n` directory.
- Updated the `docusaurus.config.js` file to include Turkish in the list of supported languages.

### CODE REVIEW

**Comment by talhademirbas** [comment]
I see that this pr ve been staying here. Even though i didn't understand whats the problem i ve put lots of effort into translating the whole documentation. I would love to fix/add stuff if somebody would assist me with what im missing.

**Comment by rrousselGit** [comment]
Sorry I'm in holidays at the moment. It's a bit big as a PR, so it'll wait until I'm back

**Comment by talhademirbas** [comment]
No problem at all. Enjoy your holiday!

**Review by rrousselGit — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
