### PR TITLE
Retry

### LINKED ISSUE #1037: Add retry support to providers

### PR DESCRIPTION
**Pull request by rrousselGit**
## Related Issues

fixes #1037

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).

- [ ] I have updated the `CHANGELOG.md` of the relevant packages.
      Changelog files must be edited under the form:

  ```md
  ## Unreleased fix/major/minor

  - Description of your change. (thanks to @yourGithubId)
  ```

- [ ] If this contains new features or behavior changes,
      I have updated the documentation to match those changes.

### CODE REVIEW

**Comment by snapsl** [comment]
@rrousselGit is this feature intended for Riverpod 3.0 or a later release?
I like the feature but I have some concerns about setting a default retry timer that can endlessly retrigger.

This approach could potentially introduce various bugs
- http libraries that have custom retry and timeout logic already in place
- unnecessary requests / rebuilds due to unresolvable error
- strange error UI behavior that would automatically resolve without user interaction
- performance degradation due to multiple providers fail simultaneously and trigger retries
- should dependent provider retry while the parent provider fail (unnecessary)
- ...

Considering these factors, handling all these cases during migration to Riverpod 3.0 could become unnecessarily complicated.
Is there already a strategy for handling this, or am I unnecessarily worried here.

**Comment by snapsl** [comment]
> It takes one line to migrate :)

This is great! I skipped the new argument on the ProviderScope.
This is probably the go to for a quick and easy upgrade. Looking forward to the release :)

> It's usually better in terms of UI if the problem fixes itself.
> The key is, you should usually use a progress indicator during the retry to show that it's retrying. A linear indicator under the appbar is usually the go-to.

Exemplary, in the async case the AsyncValue would be AsyncError during a retry, if I understand it correctly. In the default case, we  would then display an error screen with a linear ProgressIndicator that would be visible for 200ms - forever? (200ms would be very short if we display an error text)

Is there a way how we can detect if a provider is retrying (I probably missed that too :D). This would be particularly useful if only a fixed number of retries is defined.

Also, how does this concept work for a sync provider?

_Sorry for all the questions._

**Comment by snapsl** [comment]
Just checkin in briefly. Are there plans for an `isRetrying` flag?

**Comment by rrousselGit** [comment]
That's isRefreshing.

**Comment by rrousselGit** [comment]
>  This would only be true during invalidateSelf

It will be true during retries. As retries are nothing more than an invalidateSelf on error.

**Comment by snapsl** [comment]
Thank you for the clarification! 👍

**Pull request merged**
