### PR TITLE
Documentation update (#1618)

### PR DESCRIPTION
**Pull request by rrousselGit**
WIP PR for updating the site with 2.0 changes

- [x] add options to enable/disable code-generation and hooks
- [x] update all existing pages to use the new options
- [x] Add "about hooks" page
  - [x] what are hooks
  - [x] how to use hooks
- [x] Add "about code generation" page
  - [x] what is codegen
  - [x] why use codegen in riverpod
  - [x] how to use codegen
- [x] Document Notifier/AsyncNotifier
- [x] Mention in StateNotifier docs that the Notifier API is preferred

### CODE REVIEW

**Comment by chillbrodev** [comment]
I was getting ready to work on some docs for `Notifier/Async Providers` and came across this PR. Is there a task that outlines what else is needed?

**Comment by rrousselGit** [comment]
@chillbrodev Nothing super specific. There's https://github.com/rrousselGit/riverpod/issues/1762 for the global idea.

If you have any doubts, ask questions and I'll answer them.

**Comment by tbm98** [comment]
I also couldn't find a manual for dependencies when using the codegen syntax, I think you should add that to the documentation page.

**Comment by AhmedLSayed9** [comment]
Big work! Congratulation 🎆

**Comment by TheFinestArtist** [comment]
Amazing work! Thank you for the contribution 🔥

**Pull request merged**
